### ISSUE TITLE
Discussion: Separate the model in many files, one for each responsability: database, validation, etc.

### ISSUE THREAD

**Issue by melanke** [simplitech/simplicli-apiusecase#3]

**Comment by ftgibran** [comment]
I am a bit worried about the current solution of DAO files. I think it is possible to use a better solution.

Here's my new suggestion:
https://gist.github.com/ftgibran/7b25f38f841c084ec9146b9cbfd29f93

**Comment by melanke** [comment]
I still think the other solution is better because is cleaner, let's open this discussion to the team.
